### ISSUE TITLE
Composer warning outputs that this plugin is abandoned

### ISSUE THREAD

**Issue by qbunt** [lukeyouell/craft3-sentry#23]
Not saying this is correct (I suspect it's not), but Composer is now reporting this plugin is abandoned with the following message as of my last install:
```
Package lukeyouell/craft-sentry is abandoned, you should avoid using it. No replacement was suggested.
```
Maybe a version bump or something would get Composer to think the lights are back on?

**Comment by OscarBarrett** [comment]
Looks like all of @lukeyouell's composer packages are marked as abandoned, so maybe it's an issue with his account on packagist. The composer file isn't explicitly marking it as abandoned.

**Comment by jdsimcoe** [comment]
I'm seeing the same Composer output on the command line. Is there anything that the Craft CMS plugin directory does to get involved with this? I've noticed a newer Sentry plugin pop up recently in the Plugin store.

cc / @brandonkelly @angrybrad

**Comment by brandonkelly** [comment]
@jalendport has taken over several of @lukeyouell’s plugins, though Sentry is not one of them. @lukeyouell for the ones Jalen took over, maybe you can update Packagist to point to their new package names? (e.g. `lukeyouell/craft-fetch` should be suggesting `jalendport/craft-fetch`.)

**Comment by engram-design** [comment]
@jalendport Let me know if you need a hand with this plugin as well, as happy to maintain if you're not too keen - we use it a fair bit!

**Comment by lukeyouell** [comment]
Hey, apologies for the radio silence.

This year I started a new job which has meant that I've not had the time to be able to maintain the large list of plugins I previously had, due to my commute currently taking up 15 hours of my week! This is why @jalendport has taken over a bunch of my plugins.

Next month I'll be moving a lot closer to work, so I'll have time to maintain plugins such as this and get back into developing new plugins. I'm planning on giving this plugin a refresh over the weekend, so the package has been marked as no-longer being abandoned.

If you have any other questions let me know, I'll be a lot more active from now on!
